import './globals.scss'
import { Inter } from 'next/font/google'
import Navbar from '../../component/navbar/navbar'
import Footer from '../../component/footer/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* <Navbar/>
      {children} */}
      <body>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
